//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvAndDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int IdTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> MonthNumberYear { get; set; }
        public Nullable<int> WeekNumberOfYear { get; set; }
        public Nullable<int> DayNumberOfYear { get; set; }
        public Nullable<int> DayNumberOfMonth { get; set; }
        public Nullable<int> DayNumberOfWeek { get; set; }
        public string MonthName { get; set; }
        public string DayName { get; set; }
        public Nullable<bool> HolidayGermany { get; set; }
        public Nullable<bool> BankDay { get; set; }
        public Nullable<bool> isUltimo { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsLeapYear { get; set; }
        public Nullable<bool> IsLastDayOfYear { get; set; }
        public Nullable<bool> IsLastDayOfMonth { get; set; }
    }
}
